{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kortix-gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kortix-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "kortix-gateway.selectorLabels" . | nindent 6 }}
{{- end }}
